config/routes.rb
Projectman::Application.routes.draw do
  resources :reviews

  resources :shops

  resources :projects

  resources :companies

  devise_for :users
    
  authenticated :user do
    root :to => 'home#index'
  end
    
  devise_scope :user do
    get "/", :to => "devise/sessions#new"
  end

    root :to => 'home#index'

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :project
  attr_accessible :contact, :latitude, :longitude, :name
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])
    @shop.project_id = session[:current_project].to_i

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1 class="pageheader">Editing shop</h1>

	<%= render 'form' %>
	
	<%= link_to 'Show', @shop %> |
	<%= link_to 'Back', shops_path %>
</div>
<div class="span2">
	<p></p>
</div>

app/views/shops/index.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1 class="pageheader">Shops/Territories.</h1>
	<ol class="microposts">
		<% @shops.each do |shop| %>
		  <li>
		    <p>Name: <%= shop.name %></p>
		    <p>Lat: <%= shop.latitude %></p>
		    <p>Long:<%= shop.longitude %> </p>
		    <p>Contact: <%= shop.contact %></p>
		    <p>Project: <%= shop.project %></p>
		    <p>
		    	<%= link_to 'Show', shop %>
		    	<%= link_to 'Edit', edit_shop_path(shop) %>
		    	<%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %>
		    </p>
		    		    
	    	<span class="timestamp">
				Created <%= time_ago_in_words(shop.created_at) %> ago.
			</span>
		  </li>
		<% end %>
	</ol>
	
	<br />

	<%= link_to 'New Shop', new_shop_path %>
</div>
<div class="span2">
	<p>sidebar</p>
</div>

app/views/shops/new.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1 class="pageheader">New shop</h1>

	<%= render 'form' %>
	
	<%= link_to 'Back', shops_path %>
</div>
<div class="span2">
	<p></p>
</div>

app/views/shops/show.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<p id="notice"><%= notice %></p>

	<p>
	  <b>Name:</b>
	  <%= @shop.name %>
	</p>
	
	<p>
	  <b>Latitude:</b>
	  <%= @shop.latitude %>
	</p>
	
	<p>
	  <b>Longitude:</b>
	  <%= @shop.longitude %>
	</p>
	
	<p>
	  <b>Contact:</b>
	  <%= @shop.contact %>
	</p>
	
	<p>
	  <b>Project:</b>
	  <%= @shop.project %>
	</p>
	
	
	<%= link_to 'Edit', edit_shop_path(@shop) %> |
	<%= link_to 'Back', shops_path %>

</div>
<div class="span2">
	<p></p>
</div>