config/routes.rb
Projectman::Application.routes.draw do
  resources :reviews

  resources :shops

  resources :projects

  resources :companies

  devise_for :users
    
  authenticated :user do
    root :to => 'home#index'
  end
    
  devise_scope :user do
    get "/", :to => "devise/sessions#new"
  end

    root :to => 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :company
  attr_accessible :description, :homepage, :name
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    #@reviews = @project.reviews
    @reviews = Review.where(:project_id => params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
    
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.company_id = session[:current_company].to_i

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :homepage %><br />
    <%= f.text_field :homepage %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="span2">
	<p></p>	
</div>
<div class="span8">
	<h1 class="pageheader">Editing project</h1>

	<%= render 'form' %>
	
	<%= link_to 'Show', @project %> |
	<%= link_to 'Back', projects_path %>
</div>
<div class="span2">
	<p></p>
</div>

app/views/projects/index.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1 class="pageheader">Projects</h1>
	<ol class="microposts">
		<% @projects.each do |project| %>
		  <li>
		    <p><%= project.name %></p>
		    <p><%= project.description %></p>
		    <p><%= project.homepage %></p>
		    <p><%= link_to 'Show', project %>
		    <%= link_to 'Edit', edit_project_path(project) %>
		    <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></p>
		    	<span class="timestamp">
					Created <%= time_ago_in_words(project.created_at) %> ago.
				</span>
		  </li>
		<% end %>
	</ol>
	
</div>
<div class="span2">
	<p></p>
</div>

app/views/projects/new.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1 class="pageheader">New project</h1>

	<%= render 'form' %>

	<%= link_to 'Back', projects_path %>
</div>
<div class="span2">
	<p>Sidebar</p>
</div>

app/views/projects/show.html.erb
<div class="span2">
	<div>
		<% session[:current_project] = @project.id %>
    	<%= link_to 'Create New Shop/Territory.', new_shop_path %>
	</div>
	<div>
		<% session[:current_project] = @project.id %>
    	<%= link_to 'Create New Review.', new_review_path %>
	</div>
</div>
<div class="span8">
	<p id="notice"><%= notice %></p>

	<p>
	  <b>Name:</b>
	  <%= @project.name %>
	</p>
	
	<p>
	  <b>Description:</b>
	  <%= @project.description %>
	</p>
	
	<p>
	  <b>Homepage:</b>
	  <%= @project.homepage %>
	</p>
	
	<p>
	  <b>Company:</b>
	  <%= link_to @project.company.name, @project.company  %>
	</p>
	
	
	<%= link_to 'Edit', edit_project_path(@project) %> |
	<%= link_to 'Back', projects_path %>
	
	<div class="row">
		<h1 class="pageheader">This Project's Reviews</h1>

		<table>
		  <tr>
		    <th>Latitude</th>
		    <th>Longitude</th>
		    <th>Review</th>
		    <th>Data</th>
		    <th>Project</th>
		    <th>Datetime of Visit</th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>
		
		<% @reviews.each do |review| %>
		  <tr>
		    <td><%= review.latitude %></td>
		    <td><%= review.longitude %></td>
		    <td><%= review.review %></td>
		    <td><%= review.data %></td>
		    <td><%= review.project.name %></td>
		    <td><%= review.datetime_of_visit %></td>
		    <td><%= link_to 'Show', review %></td>
		    <td><%= link_to 'Edit', edit_review_path(review) %></td>
		    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
		</table>

	</div>
</div>
<div class="span2">
	<p></p>
</div>