config/routes.rb
Projectman::Application.routes.draw do
  resources :reviews

  resources :shops

  resources :projects

  resources :companies

  devise_for :users
    
  authenticated :user do
    root :to => 'home#index'
  end
    
  devise_scope :user do
    get "/", :to => "devise/sessions#new"
  end

    root :to => 'home#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :description, :homepage, :name
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :homepage %><br />
    <%= f.text_field :homepage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1 class="pageheader">Edit Company Info</h1>

	<%= render 'form' %>
	
	<%= link_to 'Show', @company %> |
	<%= link_to 'Back', companies_path %>
</div>
<div class="span2">
	<p></p>
</div>

app/views/companies/index.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1 class="pageheader">Companies</h1>
	<ol class="microposts">
		<% @companies.each do |company| %>
		  <li>
		    <p><%= company.name %></p>
		    <p><%= company.description %></p>
		    <p><%= company.homepage %></p>
		    <p><%= link_to 'Show', company %>
		    <%= link_to 'Edit', edit_company_path(company) %>
		    <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></p>
		    	<span class="timestamp">
					Created <%= time_ago_in_words(company.created_at) %> ago.
				</span>
		  </li>
		<% end %>
	</ol>
	
	<br />

	<%= link_to 'New Company', new_company_path %>
</div>
<div class="span2">
	<p>sidebar</p>
</div>

app/views/companies/new.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1 class="pageheader">New company</h1>

	<%= render 'form' %>
	
	<%= link_to 'Back', companies_path %>
</div>
<div class="span2">
	<p>sidebar</p>
</div>

app/views/companies/show.html.erb
<div class="span2">
	<% session[:current_company] = @company.id %>
    <%= link_to 'Create New Project.', new_project_path %>
</div>
<div class="span8">
	<p id="notice"><%= notice %></p>
	
	<p>
	  <b>Name:</b>
	  <%= @company.name %>
	</p>
	
	<p>
	  <b>Description:</b>
	  <%= @company.description %>
	</p>
	
	<p>
	  <b>Homepage:</b>
	  <%= @company.homepage %>
	</p>
	
	
	<%= link_to 'Edit', edit_company_path(@company) %> |
	<%= link_to 'Back', companies_path %>
</div>
<div class="span2">
	<p></p>
</div>