config/routes.rb
Projectman::Application.routes.draw do
  resources :reviews

  resources :shops

  resources :projects

  resources :companies

  devise_for :users
    
  authenticated :user do
    root :to => 'home#index'
  end
    
  devise_scope :user do
    get "/", :to => "devise/sessions#new"
  end

    root :to => 'home#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])
    @review.project_id = session[:current_project].to_i

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude, :placeholder => "Latitudde of agent" %>
  </div>

<div class="field">
   <%= f.label :longitude %>
  <div class="field">
    <%= f.text_field :longitude, :class => 'text_field', :placeholder => "Longitude of agent" %>
  </div>
</div>
<div class="field">
   <%= f.label :review %>
  <div class="field">
    <%= f.text_area :review, :class => 'text_field', :placeholder => "Review" %>
  </div>
</div>
<div class="field">
   <%= f.label :datetime_of_visit %>
  <div class="field">
    <%= f.text_field :datetime_of_visit, :class => 'text_field', :placeholder => "Datetimeof visit" %>
  </div>
</div>


<div class='clearfix attributeContainer'>
  <label class="label" for="review_data">Data Attributes</label>
  <div class='row'>
    <p class='span3 underline'>Name</p>
    <p class='span3 underline'>Value</p>
  </div>

  <%= f.fields_for :data, @review.data do |d| %>
    <% @review.data.try(:each) do |key, value| %>
        <div class="row">
          <p class='span3'>
            <%= text_field_tag key, key, :class => 'text_field dynamicAttributeName' %>
          </p>
          <p class='span3'>
            <%= d.text_field key, :class => 'text_field', :value => value %>
          </p>
          <p class='span1'>
            <a herf='#' class='btn removeRow'>X</a>
          </p>
        </div>
    <% end %>
  <%- end -%>

  <div class='row attributeTemplate <%= 'hide' if @review.data.present? %>'>
    <p class='span3'>
      <input class='text_field dynamicAttributeName' id='' name='' placeholder='New Attribute name' size='30' type='text' />
    </p>
    <p class='span3'><input class='text_field' id='bar' name='' placeholder='value' size='30' type='text' /></p>
    <p class='span1'><a herf='#' class='btn removeRow'>X</a></p>
  </div>
  <%= link_to 'Add Attribute', '#', :class => 'btn addAttribute btn-primary' %>
</div>



<div class="form-actions">
  <%= f.submit 'Save', :class => 'btn primary' %> or
<%= link_to "Cancel", request.referrer || reviews_path %>
</div>



<%= content_for :js do %>
  <script type='text/javascript'>
   $('.attributeContainer').delegate('.dynamicAttributeName', 'keyup', function(event){
     nameElem = $(this);
     valueElem = nameElem.closest('.row').children('p').children('.text_field')
     value = nameElem.val().toLowerCase();
     valueElem.attr('id', 'review_data_' + value );
     valueElem.attr('name', 'review[data][' + value + ']');
     valueElem.attr('placeholder', 'value for ' + value );
   })

   $('.attributeContainer').delegate('.removeRow', 'click', function(){
     console.log($(this).closest('.row'))
     $(this).closest('.row').html('');
   })

   $('.addAttribute').on('click', function(){
     contents = "<div class='row'>" + $('.attributeTemplate').html() + '</div>';
     $(this).before(contents);
   })
  </script>
<%- end -%>

app/views/reviews/edit.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1>Editing review</h1>

	<%= form_for  @review, :html => { :class => :form } do |f| -%>
	  <%= render :partial => "form", :locals => {:f => f} %>
	<% end -%>
	
	<%= link_to 'Show', @review %> |
	<%= link_to 'Back', reviews_path %>
</div>
<div class="span2">
	<p></p>
</div>

app/views/reviews/index.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1 class="pageheader">Reviews</h1>
	<ol class="microposts">
		<% @reviews.each do |review| %>
		  <li>
		    <p>Lat: <%= review.latitude %></p>
			<p>Long: <%= review.longitude %></p>
			<p>Review: <%= review.review %></p>
			<p>
				Data:
			        <span>
			          <%- review.data.try(:each) do |key, value| -%>
			            {'<%= key %>' => '<%= value %>'}
			          <%- end -%>
			        </span>
			</p>
			<p>Project: <%= review.project %></p>
			<p>
				<%= link_to 'Show', review %>
				<%= link_to 'Edit', edit_review_path(review) %>
				<%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %>
			</p>
		   
	    	<span class="timestamp">
				Created <%= time_ago_in_words(review.created_at) %> ago.
			</span>
		  </li>
		<% end %>
	</ol>
	
</div>
<div class="span2">
	<p></p>
</div>

app/views/reviews/new.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<h1 class="pageheader">New review</h1>

	<%= form_for @review, :html => { :class => :form } do |f| -%>
	  <%= render :partial => "form", :locals => {:f => f} %>
	<% end -%>
	
	<%= link_to 'Back', reviews_path %>
</div>
<div class="span2">
	<p></p>
</div>

app/views/reviews/show.html.erb
<div class="span2">
	<p></p>
</div>
<div class="span8">
	<p id="notice"><%= notice %></p>

	<p>
	  <b>Latitude:</b>
	  <%= @review.latitude %>
	</p>
	
	<p>
	  <b>Longitude:</b>
	  <%= @review.longitude %>
	</p>
	
	<p>
	  <b>Datetime of visit:</b>
	  <%= @review.datetime_of_visit %>
	</p>
	
	<p>
	  <b>Review:</b>
	  <%= @review.review %>
	</p>
	
	<p>
		<div class='clearfix attributeContainer'>
		  <label class="label" for="review_data">Data Attributes</label>
		  <div class='row'>
		    <p class='span3 underline'>Name</p>
		    <p class='span3 underline'>Value</p>
		  </div>
		  <% @review.data.try(:each) do |key, value| %>
		    <div class='row'>
		      <p class='span3'>
		        <%= key %>
		      </p>
		      <p class='span3'><%= value %></p>
		    </div>
		  <%- end -%>
		</div>
	</p>
	
	<p>
	  <b>Project:</b>
	  <%= @review.project.name %>
	</p>
	
	
	<%= link_to 'Edit', edit_review_path(@review) %> |
	<%= link_to 'Back', reviews_path %>

</div>
<div class="span2">
	<p></p>
</div>